package models

const (
	blockNum  = "blockNumber"
	gasPrice  = "gasPrice"
	gas       = "gas"
	nonce     = "nonce"
	txIdx     = "transactionIndex"
	val       = "value"
	v         = "v"
	r         = "r"
	s         = "s"
	blockHash = "blockHash"
	hash      = "hash"
	from      = "from"
	to        = "to"
	input     = "input"

	txs          = "transactions"
	timestamp    = "timestamp"
	size         = "size"
	number       = "number"
	gasUsed      = "gasUsed"
	gasLimit     = "gasLimit"
	diff         = "difficulty"
	extraData    = "extraData"
	data         = "data"
	miner        = "miner"
	stateRoot    = "stateRoot"
	receiptsRoot = "receiptsRoot"
	txsRoot      = "transactionsRoot"
	sha3Uncles   = "sha3Uncles"
	parentHash   = "parentHash"
	logsBloom    = "logsBloom"
	uncles       = "uncles"

	removed = "removed"
	topics  = "topics"
	logIdx  = "logIndex"
	txHash  = "transactionHash"
	address = "address"
)
