// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: extra.proto

package extra

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtraTx struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	GasPrice             string                 `protobuf:"bytes,1,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	Gas                  string                 `protobuf:"bytes,2,opt,name=gas,proto3" json:"gas,omitempty"`
	Nonce                string                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TransactionIndex     string                 `protobuf:"bytes,4,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	BlockHash            string                 `protobuf:"bytes,5,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	Access               []*AccessList          `protobuf:"bytes,6,rep,name=access,proto3" json:"access,omitempty"`
	MaxFeePerGas         string                 `protobuf:"bytes,7,opt,name=maxFeePerGas,proto3" json:"maxFeePerGas,omitempty"`
	MaxPriorityFeePerGas string                 `protobuf:"bytes,8,opt,name=maxPriorityFeePerGas,proto3" json:"maxPriorityFeePerGas,omitempty"`
	MaxFeePerBlobGas     string                 `protobuf:"bytes,9,opt,name=maxFeePerBlobGas,proto3" json:"maxFeePerBlobGas,omitempty"`
	BlobVersionedHashes  string                 `protobuf:"bytes,10,opt,name=blobVersionedHashes,proto3" json:"blobVersionedHashes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ExtraTx) Reset() {
	*x = ExtraTx{}
	mi := &file_extra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraTx) ProtoMessage() {}

func (x *ExtraTx) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraTx.ProtoReflect.Descriptor instead.
func (*ExtraTx) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{0}
}

func (x *ExtraTx) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *ExtraTx) GetGas() string {
	if x != nil {
		return x.Gas
	}
	return ""
}

func (x *ExtraTx) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ExtraTx) GetTransactionIndex() string {
	if x != nil {
		return x.TransactionIndex
	}
	return ""
}

func (x *ExtraTx) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *ExtraTx) GetAccess() []*AccessList {
	if x != nil {
		return x.Access
	}
	return nil
}

func (x *ExtraTx) GetMaxFeePerGas() string {
	if x != nil {
		return x.MaxFeePerGas
	}
	return ""
}

func (x *ExtraTx) GetMaxPriorityFeePerGas() string {
	if x != nil {
		return x.MaxPriorityFeePerGas
	}
	return ""
}

func (x *ExtraTx) GetMaxFeePerBlobGas() string {
	if x != nil {
		return x.MaxFeePerBlobGas
	}
	return ""
}

func (x *ExtraTx) GetBlobVersionedHashes() string {
	if x != nil {
		return x.BlobVersionedHashes
	}
	return ""
}

type AccessList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessList) Reset() {
	*x = AccessList{}
	mi := &file_extra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessList) ProtoMessage() {}

func (x *AccessList) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessList.ProtoReflect.Descriptor instead.
func (*AccessList) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{1}
}

func (x *AccessList) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ExtraBlock struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uncles           []*Uncle               `protobuf:"bytes,1,rep,name=uncles,proto3" json:"uncles,omitempty"`
	BlockHash        string                 `protobuf:"bytes,2,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	GasUsed          string                 `protobuf:"bytes,3,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	GasLimit         string                 `protobuf:"bytes,4,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	Difficulty       string                 `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	ExtraData        string                 `protobuf:"bytes,6,opt,name=extraData,proto3" json:"extraData,omitempty"`
	Hash             string                 `protobuf:"bytes,7,opt,name=hash,proto3" json:"hash,omitempty"`
	Nonce            string                 `protobuf:"bytes,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Miner            string                 `protobuf:"bytes,9,opt,name=miner,proto3" json:"miner,omitempty"`
	StateRoot        string                 `protobuf:"bytes,10,opt,name=stateRoot,proto3" json:"stateRoot,omitempty"`
	ReceiptsRoot     string                 `protobuf:"bytes,11,opt,name=receiptsRoot,proto3" json:"receiptsRoot,omitempty"`
	TransactionsRoot string                 `protobuf:"bytes,12,opt,name=transactionsRoot,proto3" json:"transactionsRoot,omitempty"`
	Sha3Uncles       string                 `protobuf:"bytes,13,opt,name=sha3Uncles,proto3" json:"sha3Uncles,omitempty"`
	ParentHash       string                 `protobuf:"bytes,14,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	LogsBloom        string                 `protobuf:"bytes,15,opt,name=logsBloom,proto3" json:"logsBloom,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExtraBlock) Reset() {
	*x = ExtraBlock{}
	mi := &file_extra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraBlock) ProtoMessage() {}

func (x *ExtraBlock) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraBlock.ProtoReflect.Descriptor instead.
func (*ExtraBlock) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{2}
}

func (x *ExtraBlock) GetUncles() []*Uncle {
	if x != nil {
		return x.Uncles
	}
	return nil
}

func (x *ExtraBlock) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *ExtraBlock) GetGasUsed() string {
	if x != nil {
		return x.GasUsed
	}
	return ""
}

func (x *ExtraBlock) GetGasLimit() string {
	if x != nil {
		return x.GasLimit
	}
	return ""
}

func (x *ExtraBlock) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *ExtraBlock) GetExtraData() string {
	if x != nil {
		return x.ExtraData
	}
	return ""
}

func (x *ExtraBlock) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ExtraBlock) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ExtraBlock) GetMiner() string {
	if x != nil {
		return x.Miner
	}
	return ""
}

func (x *ExtraBlock) GetStateRoot() string {
	if x != nil {
		return x.StateRoot
	}
	return ""
}

func (x *ExtraBlock) GetReceiptsRoot() string {
	if x != nil {
		return x.ReceiptsRoot
	}
	return ""
}

func (x *ExtraBlock) GetTransactionsRoot() string {
	if x != nil {
		return x.TransactionsRoot
	}
	return ""
}

func (x *ExtraBlock) GetSha3Uncles() string {
	if x != nil {
		return x.Sha3Uncles
	}
	return ""
}

func (x *ExtraBlock) GetParentHash() string {
	if x != nil {
		return x.ParentHash
	}
	return ""
}

func (x *ExtraBlock) GetLogsBloom() string {
	if x != nil {
		return x.LogsBloom
	}
	return ""
}

type Uncle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Uncle) Reset() {
	*x = Uncle{}
	mi := &file_extra_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uncle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uncle) ProtoMessage() {}

func (x *Uncle) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uncle.ProtoReflect.Descriptor instead.
func (*Uncle) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{3}
}

func (x *Uncle) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type ExtraReceipt struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LogsBloom         string                 `protobuf:"bytes,1,opt,name=logsBloom,proto3" json:"logsBloom,omitempty"`
	Root              string                 `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	EffectiveGasPrice string                 `protobuf:"bytes,3,opt,name=effectiveGasPrice,proto3" json:"effectiveGasPrice,omitempty"`
	CumulativeGasUsed string                 `protobuf:"bytes,4,opt,name=cumulativeGasUsed,proto3" json:"cumulativeGasUsed,omitempty"`
	GasUsed           string                 `protobuf:"bytes,5,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExtraReceipt) Reset() {
	*x = ExtraReceipt{}
	mi := &file_extra_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraReceipt) ProtoMessage() {}

func (x *ExtraReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraReceipt.ProtoReflect.Descriptor instead.
func (*ExtraReceipt) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{4}
}

func (x *ExtraReceipt) GetLogsBloom() string {
	if x != nil {
		return x.LogsBloom
	}
	return ""
}

func (x *ExtraReceipt) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *ExtraReceipt) GetEffectiveGasPrice() string {
	if x != nil {
		return x.EffectiveGasPrice
	}
	return ""
}

func (x *ExtraReceipt) GetCumulativeGasUsed() string {
	if x != nil {
		return x.CumulativeGasUsed
	}
	return ""
}

func (x *ExtraReceipt) GetGasUsed() string {
	if x != nil {
		return x.GasUsed
	}
	return ""
}

var File_extra_proto protoreflect.FileDescriptor

const file_extra_proto_rawDesc = "" +
	"\n" +
	"\vextra.proto\"\xf2\x02\n" +
	"\aExtraTx\x12\x1a\n" +
	"\bgasPrice\x18\x01 \x01(\tR\bgasPrice\x12\x10\n" +
	"\x03gas\x18\x02 \x01(\tR\x03gas\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\tR\x05nonce\x12*\n" +
	"\x10transactionIndex\x18\x04 \x01(\tR\x10transactionIndex\x12\x1c\n" +
	"\tblockHash\x18\x05 \x01(\tR\tblockHash\x12#\n" +
	"\x06access\x18\x06 \x03(\v2\v.accessListR\x06access\x12\"\n" +
	"\fmaxFeePerGas\x18\a \x01(\tR\fmaxFeePerGas\x122\n" +
	"\x14maxPriorityFeePerGas\x18\b \x01(\tR\x14maxPriorityFeePerGas\x12*\n" +
	"\x10maxFeePerBlobGas\x18\t \x01(\tR\x10maxFeePerBlobGas\x120\n" +
	"\x13blobVersionedHashes\x18\n" +
	" \x01(\tR\x13blobVersionedHashes\"&\n" +
	"\n" +
	"accessList\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\xca\x03\n" +
	"\n" +
	"ExtraBlock\x12\x1e\n" +
	"\x06uncles\x18\x01 \x03(\v2\x06.uncleR\x06uncles\x12\x1c\n" +
	"\tblockHash\x18\x02 \x01(\tR\tblockHash\x12\x18\n" +
	"\agasUsed\x18\x03 \x01(\tR\agasUsed\x12\x1a\n" +
	"\bgasLimit\x18\x04 \x01(\tR\bgasLimit\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\tR\n" +
	"difficulty\x12\x1c\n" +
	"\textraData\x18\x06 \x01(\tR\textraData\x12\x12\n" +
	"\x04hash\x18\a \x01(\tR\x04hash\x12\x14\n" +
	"\x05nonce\x18\b \x01(\tR\x05nonce\x12\x14\n" +
	"\x05miner\x18\t \x01(\tR\x05miner\x12\x1c\n" +
	"\tstateRoot\x18\n" +
	" \x01(\tR\tstateRoot\x12\"\n" +
	"\freceiptsRoot\x18\v \x01(\tR\freceiptsRoot\x12*\n" +
	"\x10transactionsRoot\x18\f \x01(\tR\x10transactionsRoot\x12\x1e\n" +
	"\n" +
	"sha3Uncles\x18\r \x01(\tR\n" +
	"sha3Uncles\x12\x1e\n" +
	"\n" +
	"parentHash\x18\x0e \x01(\tR\n" +
	"parentHash\x12\x1c\n" +
	"\tlogsBloom\x18\x0f \x01(\tR\tlogsBloom\"\x1b\n" +
	"\x05uncle\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"\xb6\x01\n" +
	"\fExtraReceipt\x12\x1c\n" +
	"\tlogsBloom\x18\x01 \x01(\tR\tlogsBloom\x12\x12\n" +
	"\x04root\x18\x02 \x01(\tR\x04root\x12,\n" +
	"\x11effectiveGasPrice\x18\x03 \x01(\tR\x11effectiveGasPrice\x12,\n" +
	"\x11cumulativeGasUsed\x18\x04 \x01(\tR\x11cumulativeGasUsed\x12\x18\n" +
	"\agasUsed\x18\x05 \x01(\tR\agasUsedB\rZ\vproto/extrab\x06proto3"

var (
	file_extra_proto_rawDescOnce sync.Once
	file_extra_proto_rawDescData []byte
)

func file_extra_proto_rawDescGZIP() []byte {
	file_extra_proto_rawDescOnce.Do(func() {
		file_extra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extra_proto_rawDesc), len(file_extra_proto_rawDesc)))
	})
	return file_extra_proto_rawDescData
}

var file_extra_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_extra_proto_goTypes = []any{
	(*ExtraTx)(nil),      // 0: ExtraTx
	(*AccessList)(nil),   // 1: accessList
	(*ExtraBlock)(nil),   // 2: ExtraBlock
	(*Uncle)(nil),        // 3: uncle
	(*ExtraReceipt)(nil), // 4: ExtraReceipt
}
var file_extra_proto_depIdxs = []int32{
	1, // 0: ExtraTx.access:type_name -> accessList
	3, // 1: ExtraBlock.uncles:type_name -> uncle
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_extra_proto_init() }
func file_extra_proto_init() {
	if File_extra_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extra_proto_rawDesc), len(file_extra_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extra_proto_goTypes,
		DependencyIndexes: file_extra_proto_depIdxs,
		MessageInfos:      file_extra_proto_msgTypes,
	}.Build()
	File_extra_proto = out.File
	file_extra_proto_goTypes = nil
	file_extra_proto_depIdxs = nil
}
